modLoader = "javafml"
loaderVersion = "[40,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/PanSzelescik/proxy-protocol-support/issues"
[[mods]]
modId="proxy_protocol"
version="${file.jarVersion}"
displayName="proxy-protocol"
displayURL="https://www.curseforge.com/minecraft/mc-mods/proxy-protocol-support"
authors="PanSzelescik"
displayTest="IGNORE_ALL_VERSION"
description='''
proxy-protocol support for Forge servers
'''
[[dependencies.proxy_protocol]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
